# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt2', '0002_auto_20161026_1140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add',
            new_name='Join',
        ),
        migrations.RenameField(
            model_name='join',
            old_name='newquote',
            new_name='quote',
        ),
        migrations.RenameField(
            model_name='quotes',
            old_name='quote',
            new_name='message',
        ),
    ]
